// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: embeddings.sql

package dbgen

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const deleteEmbedding = `-- name: DeleteEmbedding :exec
DELETE FROM bounty_embeddings
WHERE bounty_id = $1
`

func (q *Queries) DeleteEmbedding(ctx context.Context, bountyID string) error {
	_, err := q.db.Exec(ctx, deleteEmbedding, bountyID)
	return err
}

const insertEmbedding = `-- name: InsertEmbedding :exec
INSERT INTO bounty_embeddings (bounty_id, embedding)
VALUES ($1, $2)
ON CONFLICT (bounty_id) DO UPDATE SET
embedding = EXCLUDED.embedding
`

type InsertEmbeddingParams struct {
	BountyID  string          `json:"bounty_id"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error {
	_, err := q.db.Exec(ctx, insertEmbedding, arg.BountyID, arg.Embedding)
	return err
}

const searchEmbeddings = `-- name: SearchEmbeddings :many
SELECT bounty_id, embedding
FROM bounty_embeddings
ORDER BY embedding <=> $1
LIMIT $2
`

type SearchEmbeddingsParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	RowCount  int32           `json:"row_count"`
}

func (q *Queries) SearchEmbeddings(ctx context.Context, arg SearchEmbeddingsParams) ([]BountyEmbedding, error) {
	rows, err := q.db.Query(ctx, searchEmbeddings, arg.Embedding, arg.RowCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BountyEmbedding
	for rows.Next() {
		var i BountyEmbedding
		if err := rows.Scan(&i.BountyID, &i.Embedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
