// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"github.com/pgvector/pgvector-go"
)

type BountyEmbedding struct {
	BountyID  string          `json:"bounty_id"`
	Embedding pgvector.Vector `json:"embedding"`
}
