// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateContactUsSubmission(ctx context.Context, arg CreateContactUsSubmissionParams) (ContactUsSubmission, error)
	DeleteEmbedding(ctx context.Context, bountyID string) error
	DeleteEmbeddings(ctx context.Context, bountyIds string) error
	DeleteEmbeddingsNotIn(ctx context.Context, bountyIds string) error
	GetAllContactUsSubmissions(ctx context.Context, arg GetAllContactUsSubmissionsParams) ([]ContactUsSubmission, error)
	GetBountySummary(ctx context.Context, bountyID string) ([]byte, error)
	GetContactUsSubmission(ctx context.Context, id int32) (ContactUsSubmission, error)
	GetExistingGumroadSaleIDs(ctx context.Context, saleIds []string) ([]string, error)
	GetLatestSolanaTransactionForRecipient(ctx context.Context, recipientWallet string) (SolanaTransaction, error)
	GetSolanaTransactionsByBountyID(ctx context.Context, bountyID pgtype.Text) ([]SolanaTransaction, error)
	GetUnnotifiedGumroadSales(ctx context.Context) ([]GumroadSale, error)
	InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error
	InsertGumroadSale(ctx context.Context, arg InsertGumroadSaleParams) error
	InsertSolanaTransaction(ctx context.Context, arg InsertSolanaTransactionParams) (SolanaTransaction, error)
	ListBountyIDs(ctx context.Context) ([]string, error)
	SearchEmbeddings(ctx context.Context, arg SearchEmbeddingsParams) ([]SearchEmbeddingsRow, error)
	UpdateBountySummary(ctx context.Context, arg UpdateBountySummaryParams) error
	UpdateGumroadSaleNotification(ctx context.Context, arg UpdateGumroadSaleNotificationParams) error
	UpsertBountySummary(ctx context.Context, arg UpsertBountySummaryParams) error
}

var _ Querier = (*Queries)(nil)
