// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteEmbedding(ctx context.Context, bountyID string) error
	DeleteEmbeddings(ctx context.Context, bountyIds string) error
	DeleteEmbeddingsNotIn(ctx context.Context, bountyIds string) error
	GetBountySummary(ctx context.Context, bountyID string) ([]byte, error)
	GetUnnotifiedGumroadSales(ctx context.Context, minSaleTimestamp pgtype.Timestamptz) ([]GumroadSale, error)
	InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error
	InsertGumroadSale(ctx context.Context, arg InsertGumroadSaleParams) (GumroadSale, error)
	ListBountyIDs(ctx context.Context) ([]string, error)
	SearchEmbeddings(ctx context.Context, arg SearchEmbeddingsParams) ([]BountyEmbedding, error)
	UpdateBountySummary(ctx context.Context, arg UpdateBountySummaryParams) error
	UpdateGumroadSaleNotification(ctx context.Context, arg UpdateGumroadSaleNotificationParams) error
	UpsertBountySummary(ctx context.Context, arg UpsertBountySummaryParams) error
}

var _ Querier = (*Queries)(nil)
