// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"context"
)

type Querier interface {
	DeleteEmbedding(ctx context.Context, bountyID string) error
	InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error
	SearchEmbeddings(ctx context.Context, arg SearchEmbeddingsParams) ([]BountyEmbedding, error)
}

var _ Querier = (*Queries)(nil)
